logging:
  level:
    ROOT: INFO
    ir.kit.github.phonebook: INFO

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: KitGithubIntegration
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

application:
  github:
    github-url: 'https://api.github.com'
  mongodb:
    mongo-uri: 'mongodb://kitgithubphonebook-mongodb:27017'
  http:
    cache:
      timeToLiveInDays: 1461
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 1000
  metrics:
    logs:
      enabled: false
      report-frequency: 60