logging:
  level:
    ROOT: DEBUG
    ir.snapp.github.integration: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: SnappGithubIntegration
  messages:
    cache-duration: PT1S

server:
  port: 8080

application:
  github:
    github-url: 'https://api.github.com'
  mongodb:
    mongo-uri: 'mongodb://localhost:27017'
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  metrics:
    logs:
      enabled: false
      report-frequency: 60