version: '2'
services:
  kitgithubphonebook-app:
    image: kitgithubphonebook
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://kitgithubphonebook-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=KitGithubIntegration
    ports:
      - 8080:8080
  kitgithubphonebook-mongodb:
    extends:
      file: mongodb.yml
      service: kitgithubphonebook-mongodb
