version: '2'
services:
  snappgithubintegration-app:
    image: snappgithubintegration
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://snappgithubintegration-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=SnappGithubIntegration
    ports:
      - 8080:8080
  snappgithubintegration-mongodb:
    extends:
      file: mongodb.yml
      service: snappgithubintegration-mongodb
